name: Go CI

on:
  push:
    branches:
      - main  # Change this to your default branch name
  pull_request:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.1'  # Specify the Go version you want to use

    # - name: Build
    #   run: go build -v ./../...  # Build the entire project

    - name: Run Tests
      run: | # Run all tests in the project
          for d in */ ; do
            echo "Running tests for $d"
            cd $d
            go test ./...
            cd ..
          done 
